name: store_shared_models
description: Shared models for store navigation app
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
